#include "icmp_protocol.h"
#include "protocol_headers.h"
#include "common.h"
#include <string.h>

void turnICMPEchoRequestInReply(struct icmp_hdr *packet, int packetLen)
{
  packet->icmp_type = 0x00;

  packet->icmp_csum = 0x0000;
  // compute checksum
  packet->icmp_csum = computeChecksum((unsigned short*) packet, packetLen*2);
}

void setICMPTLEMessage(char *buffer, char *ipDGram, unsigned short numBytes2Copy)
{
  struct icmp_hdr *packet = (struct icmp_hdr*) buffer;
  packet->icmp_type = 0x0B; // 11
  // since the router do not implements fragment reassembly
  // the tle messages will be alway generated by ttl = 0
  packet->icmp_code = 0;
  packet->icmp_csum = 0x0000;
  packet->icmp_id = packet->icmp_seqnum = 0;

  // copys the ip header and the its first 8 bytes
  memcpy(buffer+sizeof(struct icmp_hdr), ipDGram, numBytes2Copy);
}
